[package]
name = "particle_boron"
version.workspace = true
authors = [
    "Tock Project Developers <tock-dev@googlegroups.com>",
    "Wilfred Mallawa <vindulawilfred@gmail.com>"
    ]
build = "build.rs"
edition.workspace = true

[dependencies]
components = { path = "../components" }
cortexm4 = { path = "../../arch/cortex-m4" }
capsules = { path = "../../capsules" }
kernel = { path = "../../kernel" }
nrf52 = { path = "../../chips/nrf52" }
nrf52840 = { path = "../../chips/nrf52840" }
nrf52_components = { path = "../nordic/nrf52_components" }
