[package]
name = "nrf5x"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
kernel = { path = "../../kernel" }
enum_primitive = { path = "../../libraries/enum_primitive" }

[features]
default = []

nrf51 = []
nrf52 = []
