[package]
name = "esp32-c3"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
esp32 = { path = "../esp32" }
rv32i = { path = "../../arch/rv32i" }
kernel = { path = "../../kernel" }

