[package]
name = "hifive_inventor"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
build = "build.rs"
edition = "2021"

[dependencies]
components = { path = "../components" }
rv32i = { path = "../../arch/rv32i" }
capsules = { path = "../../capsules" }
kernel = { path = "../../kernel" }
e310_g003 = { path = "../../chips/e310_g003" }
sifive = { path = "../../chips/sifive" }
