[package]
name = "litex_vexriscv"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rv32i = { path = "../../arch/rv32i" }
kernel = { path = "../../kernel" }
litex = { path = "../litex" }
