[package]
name = "swerv"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
tock-registers = { path = "../../libraries/tock-register-interface" }
kernel = { path = "../../kernel" }
riscv-csr = { path = "../../libraries/riscv-csr" }
