[package]
name = "e310_g003"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
sifive = { path = "../sifive" }
rv32i = { path = "../../arch/rv32i" }
kernel = { path = "../../kernel" }
e310x = { path = "../e310x" }
