[package]
name = "cortexm0p"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
kernel = { path = "../../kernel" }
cortexm = { path = "../cortex-m" }
cortexm0 = { path = "../cortex-m0" }
