[package]
name = "swervolf-eh1"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
swerv = { path = "../swerv" }
rv32i = { path = "../../arch/rv32i" }
kernel = { path = "../../kernel" }

