[package]
name = "arty_e21_chip"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
sifive = { path = "../sifive" }
rv32i = { path = "../../arch/rv32i" }
kernel = { path = "../../kernel" }

