[package]
name = "rp2040"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
cortexm0p = { path="../../arch/cortex-m0p" }
kernel = { path = "../../kernel" }
enum_primitive = { path = "../../libraries/enum_primitive" }


