[package]
name = "nano_rp2040_connect"
version.workspace = true
authors.workspace = true
build = "build.rs"
edition.workspace = true

[dependencies]
cortexm0p = { path = "../../arch/cortex-m0p" }
capsules = { path = "../../capsules" }
kernel = { path = "../../kernel" }
rp2040 = { path = "../../chips/rp2040" }
components = { path = "../components" }
enum_primitive = { path = "../../libraries/enum_primitive" }

