[package]
name = "nrf52833"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
cortexm4 = { path = "../../arch/cortex-m4" }
kernel = { path = "../../kernel" }
nrf52 = { path = "../nrf52" }
