[package]
name = "litex_sim"
version.workspace = true
authors.workspace = true
build = "build.rs"
edition.workspace = true

[dependencies]
components = { path = "../../components" }
rv32i = { path = "../../../arch/rv32i" }
kernel = { path = "../../../kernel" }
litex_vexriscv = { path = "../../../chips/litex_vexriscv" }

capsules-core = { path = "../../../capsules/core" }
capsules-extra = { path = "../../../capsules/extra" }
