[package]
name = "litex_sim"
version.workspace = true
authors.workspace = true
build = "build.rs"
edition.workspace = true

[dependencies]
components = { path = "../../components" }
rv32i = { path = "../../../arch/rv32i" }
capsules = { path = "../../../capsules" }
kernel = { path = "../../../kernel" }
litex_vexriscv = { path = "../../../chips/litex_vexriscv" }
