[package]
name = "nrf52dk"
version.workspace = true
authors.workspace = true
build = "build.rs"
edition.workspace = true

[dependencies]
components = { path = "../../components" }
cortexm4 = { path = "../../../arch/cortex-m4" }
capsules = { path = "../../../capsules" }
kernel = { path = "../../../kernel" }
nrf52832 = { path = "../../../chips/nrf52832" }
nrf52_components = { path = "../nrf52_components" }
